FROM node:14
LABEL Philipp Fleischer <philipp.fleischer0@gmail.com>

RUN git clone https://github.com/berliner-webschmiede/posztgres

WORKDIR /posztgres
RUN npm install
RUN npx prisma migrate dev --preview-feature
EXPOSE 4466
EXPOSE 5555

