# docker-compose.yml
version: '3'
services:
  postgres-db:
    image: postgres:10-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydb
      listen_addresses: '127.0.0.1'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prisma:
    build:
      context: .
      dockerfile: Dockerfile-backend
    restart: always
    ports:
      - '4466:4466'
      - "5555:5555"
    depends_on: 
       postgres-db:
                  condition: "service_healthy"
    command: ["npx", "prisma studio","prisma migrate dev --preview-feature"]
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: mysecret42
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: prisma
            password: prisma
            database: mydb
            schema: public
            migrations: true

