# docker-compose.yml
version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@0.0.0.0:5432/cyber?schema=public
    ports:
      - "5555:5555"

  postgres:
    build: 
      context: ./DB/.
      dockerfile: Dockerfile-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cyber
